set(_AMENT_PACKAGE_NAME "platform_gui")
set(platform_gui_VERSION "0.0.0")
set(platform_gui_MAINTAINER "park <61260130+parkdg44@users.noreply.github.com>")
set(platform_gui_BUILD_DEPENDS "rclcpp" "std_msgs" "cv_bridge" "sensor_msgs" "image_transport" "qtbase5-dev" "qt5-qmake")
set(platform_gui_BUILDTOOL_DEPENDS "ament_cmake")
set(platform_gui_BUILD_EXPORT_DEPENDS )
set(platform_gui_BUILDTOOL_EXPORT_DEPENDS )
set(platform_gui_EXEC_DEPENDS "libqt5-core" "rclcpp" "std_msgs")
set(platform_gui_TEST_DEPENDS )
set(platform_gui_GROUP_DEPENDS )
set(platform_gui_MEMBER_OF_GROUPS )
set(platform_gui_DEPRECATED "")
set(platform_gui_EXPORT_TAGS)
list(APPEND platform_gui_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
